---
title: "New record of <i>Oryctanthus grammatus</i> (Loranthaceae), a parasitic plant known only from the type collection"
type: "article"
author:
  - name: "**Isabel Carmona-Gallego**"
    orcid: 0000-0001-8954-4503
  - name: "**Jhon Steven Murillo-Serna**"
    orcid: 0000-0003-4512-5811
  - name: "**Francisco Javier Roldán-Palacio**"
    orcid: 0000-0001-9241-9551
  - name: "**Fernando Alveiro Alzate-Guarin**"
    orcid: 0000-0002-4916-8897
year: 2019
date: 2019-11-15
publication: Revista de la Academia Colombiana de Ciencias Exactas, Físicas y Naturales
doi: https://doi.org/10.18257/raccefyn.921
materials: ""

categories:
  - Biological collections
  - Flora of Antioquia
  - Flora of Colombia
  - Loranthaceae
  - Santalales

---

## Abstract

*Oryctanthus grammatus* is a species described in 2011 and found in the biogeographic area of the Magdalena River, Colombia, which is known only from the type specimen collected in 1916 in the Department of Bolívar. We report here an additional specimen found 71 years later in the Department of Antioquia, which makes it the second record of this species. We discuss here the taxonomic affinities of the species and we emphasize the value of historical collections for the knowledge of biodiversity.

## Citation

> Carmona-Gallego, I., Murillo-Serna, J. S., Roldán-Palacio, F. J., & Alzate-Guarín, F. A. (2019). New record of *Oryctanthus grammatus* (Loranthaceae), a parasitic plant known only from the type collection. *Revista de La Academia Colombiana de Ciencias Exactas, Físicas y Naturales*, 43(169), 699–704. https://doi.org/10.18257/raccefyn.921