---
title: "<i>Conchocarpus kallunkiae</i> (Rutaceae: Galipeinae), a new endemic species from the tropical rainforest in the Magdalena River Valley in Colombia"
type: "article"
author:
  - name: "**Yeison Londoño-Echeverri**"
    orcid: 0000-0001-5169-598X
  - name: "**Ana María Trujillo-López**"
    orcid: 0000-0002-0898-1646
  - name: Jorge Andrés Pérez-Zabala
  - name: Milton Groppo
year: 2021
date: 2021-01-19
publication: Brittonia
doi: https://doi.org/10.1007/s12228-021-09671-y
materials: ""

categories:
  - Endangered species
  - Neotropical diversity
  - Plant taxonomy
  - Samaná norte river
  - Sapindales

---

## Abstract

*Conchocarpus kallunkiae* (Rutaceae: Galipeinae), a new species from the Magdalena River Valley region in Colombia, is described and illustrated and comments about its geographical distribution, phenology, conservation status, and taxonomic affinities are provided. The new species differs from any other species in the genus by the combination of remarkably bullate blades, basally appendaged anthers, and a 4-carpellate ovary. Based on inflorescences and flowers, it seems closely related to *Conchocarpus macrophyllus* (type species of the genus) with which it shares foliaceus primary bracts, partial inflorescences developing as scaly short-shoots, zygomorphic flowers, an androecium of two stamens and five staminodes, and a glabrous ovary. Because it is endemic to the inter-Andean valleys of Colombia and exhibits some traits uncommon among the Galipeinae (for example, anthers connate by their basal appendages), including this species in future evolutionary studies may provide insights about the geographical and morphological histories of the genus and the subtribe.

## Citation

> Londoño-Echeverri, Y., Trujillo-López, A. M., Pérez-Zabala, J. A., & Groppo, M. (2021). *Conchocarpus kallunkiae* (Rutaceae: Galipeinae), a new endemic species from the tropical rainforest in the Magdalena River Valley in Colombia. *Brittonia*, 73(4), 422–430. https://doi.org/10.1007/s12228-021-09671-y