project:
  type: website

lang: es

website:
  title: "Grupo de Estudios Botánicos GEOBOTA"
  navbar:
    logo: images/geobota_logo.png
    right:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca
      - href: members.qmd
        text: Integrantes
      - href: news.qmd
        text: Noticias
      - href: projects.qmd
        text: Proyectos
      - href: publications.qmd
        text: Publicaciones

format:
  html:
    theme: simplex
    css: styles.css
    toc: false