project:
  type: website

lang: es
date-format: iso

execute:
    freeze: auto

website:
  title: "Grupo de Estudios Botánicos GEOBOTA"
  site-url: http://geobota.github.io
  repo-url: https://github.com/geobota/geobota.github.io
  favicon: images/logo/favicon.png
  
  page-navigation: true
  back-to-top-navigation: true

  google-analytics: 
    tracking-id: "G-6X3G195Q2V"
    anonymize-ip: true

  navbar:
    logo: images/logo/geobota_logo.png
    search: true
    right:
      - href: index.qmd
        text: Inicio
      - href: about/index.qmd
        text: Acerca
      - href: people/index.qmd
        text: Integrantes
      - href: projects/index.qmd
        text: Proyectos
      - href: publications/index.qmd
        text: Publicaciones
      - href: news/index.qmd
        text: Noticias

  page-footer: 
    left: GEOBOTA 2024, [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
    right: by [@alexespinocaco](https://alexespinosaco.github.io) with [Quarto](https://quarto.org/)

format:
  html:
    theme: simplex
    toc: false

resources: images/logo/placeholder.png