project:
  type: website

lang: es
date-format: iso

execute:
    freeze: auto

website:
  title: "Grupo de Estudios Botánicos GEOBOTA"
  description: "Website del Grupo de Estudios Botánicos GEOBOTA"
  site-url: http://geobota.github.io
  repo-url: https://github.com/geobota/geobota.github.io
  favicon: images/logo/favicon.png
  image: images/logo/geobota_logo.png
  
  page-navigation: false
  back-to-top-navigation: true
  bread-crumbs: true

  google-analytics: 
    tracking-id: "G-6X3G195Q2V"
    anonymize-ip: true

  twitter-card: 
    card-style: summary_large_image

  open-graph: true

  navbar:
    logo: images/logo/geobota_logo.png
    # background: light
    search: true
    right:
      - text: "Inicio"
        href: index.qmd
      - text: "Acerca"
        href: about/index.qmd
      - text: "Herbario"
        href: herbarium/index.qmd
      - text: "Integrantes"
        href: people/index.qmd
      - text: "Noticias"
        href: news/index.qmd
      - text: "Proyectos"
        href: projects/index.qmd
      - text: "Publicaciones"
        href: publications/index.qmd
      # - text: "XII CCB"
      #   menu:
      #     - text: "XII CCB"
      #       href: xii-ccb/index.qmd
      #     - text: "Etnobotánica Cuantitativa en R"
      #       href: https://geobota.github.io/xii-ccb-etnobotanica/
      #     - text: "Introducción a la Aerobiología"
      #       href: https://geobota.github.io/xii-ccb-aerobiologia/
      #     - text: "Investigación Reproducible con Quarto"
      #       href: https://geobota.github.io/xii-ccb-quarto/
      - icon: facebook
        href: https://www.facebook.com/geobotaudea
      - icon: instagram
        href: https://www.instagram.com/geobotaudea/
      - icon: github
        # text: "{{< fa brands github >}}"
        href: https://github.com/geobota
      - icon: rss-fill
        # text: "{{< fa square-rss >}}"
        href: atom.xml

  sidebar:

    - id: home
      contents:
        - href: index.qmd
          text: Inicio

    - id: about
      contents:
        - href: about/index.qmd
          text: Acerca

    - id: herbarium
      contents:
        - href: herbarium/index.qmd
          text: Herbario

    # - id: people
    #   contents:
    #     - section: Integrantes
    #       href: people/index.qmd
    #       contents:
    #         - auto: people/**/index.qmd

    - id: projects
      contents:
        - href: projects/index.qmd
          text: Proyectos

    - id: publications
      contents:
        - section: Publications
          href: publications/index.qmd
          contents: 
            - section: Articles
              href: publications/index.qmd#articles
              contents:
              - auto: publications/articles/**/index.qmd
            - section: Books
              href: publications/index.qmd#books
              contents:
              - auto: publications/books/**/index.qmd

    - id: news
      contents:
        - section: News
          href: news/index.qmd
          contents:
            - auto: news/*/index.qmd

    # - id: xii-ccb
    #   contents:
    #     - section: "XII CCB"
    #       href: xii-ccb/index.qmd
    #       contents: 
    #         - section: Ponencias
    #           href: xii-ccb/index.qmd#presentations
    #           contents:
    #           - auto: xii-ccb/presentations/**/index.qmd
    #         - section: Pósters
    #           href: xii-ccb/index.qmd#posters
    #           contents:
    #           - auto: xii-ccb/posters/**/index.qmd


  page-footer: 
    left: GEOBOTA © 2024-2025 is licensed under [CC BY 4.0 {{< fa brands creative-commons >}}{{< fa brands creative-commons-by >}}](https://creativecommons.org/licenses/by/4.0/)
    right: Made by [@alexespinosaco](https://alexespinosaco.github.io) with {{< fa brands r-project >}} and [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)

format:
  html:
    theme: 
      light: cosmo
      dark: solar
    css: styles.scss
    toc: false

resources:
  - images/logo/placeholder.png
  - resources
