project:
  type: website

lang: es

website:
  title: "Grupo de Estudios Botánicos GEOBOTA"
  site-url: http://geobota.github.io
  repo-url: https://github.com/geobota/geobota.github.io
  
  navbar:
    logo: images/geobota_logo.png
    search: true
    right:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca
      - href: members.qmd
        text: Integrantes
      - href: news.qmd
        text: Noticias
      - href: projects.qmd
        text: Proyectos
      - href: publications.qmd
        text: Publicaciones

  page-footer: 
    left: GEOBOTA 2023, [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
    right: by [@alexespinocaco](https://alexespinosaco.github.io) with [Quarto](https://quarto.org/)

format:
  html:
    theme: simplex
    css: styles.css
    toc: false