---
title: "Taxonomic and nomenclatural novelties in Marcetieae (Melastomataceae) from Colombia: A new species of <i>Ernestia</i> and the identity of <i>Acisanthera goudotii</i>"
author:
  - name: "Diego Nunes da Silva"
  - name: "**Jhon Steven Murillo-Serna**"
    url: /people/murillo-serna_jhon-steven/index.qmd
    orcid: 0000-0003-4512-5811
  - name: "Saúl E. Hoyos-Gómez"
  - name: "Rodrigo Bernal"
  - name: "Fabián A. Michelangeli"
year: 2024
date: 2024-12-16
publication: "Phytotaxa"
doi: https://doi.org/10.11646/phytotaxa.677.2.1
materials: ""

categories:
  - Caquetá
  - Eudicots
  - Dichaetandra
  - Rheophyte
  - Synonymization
  - Typification
  - Yarí River

---

## Abstract

During the development of the taxonomic treatment of *Ernestia* we came across a taxonomic novelty and a species for which taxonomic verification was needed from Colombia. Herein, we propose *Ernestia rheophytica* a new species belonging to the sensu stricto clade of the genus, and clarify the identity of *Acisanthera goudotii*, now treated as *E. goudotii*. We also clarify the status of the original material of *E. goudotii* and propose the lectotypification of *E. ovata* and its synonymization under *E. goudotii*. *Ernestia rheophytica*, as the name indicates, is a rheophytic species, a rare habit in Melastomataceae, especially in Marcetieae.

## Citation

> Silva, D. N. da, Murillo-Serna, J. S., Hoyos-Gómez, S. E., Bernal, R., Michelangeli, F. A., Braga, J. M. A., & Guimarães, P. J. F. (2024). Taxonomic and nomenclatural novelties in Marcetieae (Melastomataceae) from Colombia: A new species of *Ernestia* and the identity of *Acisanthera goudotii*. *Phytotaxa*, 677(2), 109–124. https://doi.org/10.11646/phytotaxa.677.2.1
