---
title: "A biologically active chromone from <i>Bomarea setacea</i> (<i>Alstroemeriaceae</i>): leishmanicidal, antioxidant and multilevel computational studies"
type: "article"
author:
  - name: Wilson Cardona-Galeano
  - name: Andrés Felipe Yépes-Pérez
  - name: Jorge Quintero‐Saumeth
  - name: Sara Maria Robledo
  - name: "**Fernando Alveiro Alzate-Guarin**"
    orcid: 0000-0002-4916-8897
  - name: Benjamín Rojano
year: 2022
date: 2022-12-06
publication: ChemistrySelect
doi: https://doi.org/10.1002/slct.202203852
materials: ""

categories:
  - Antileishmanial
  - Antioxidant
  - Bomarea setacea
  - Chromone
  - In silico studies
---

## Abstract

A chromone was isolated from alcoholic extracts from Bomarea setacea and identified as 2-henicosyl-5,7-dihydroxy-4H-chromen-4-one. The leishmanicidal activity was evaluated against intracellular amastigotes of L. panamensis and cytotoxicity on U-937 cells, maintained in standard culture conditions. This compound showed leishmanicidal activity (EC~50=~14.8±1.9 μg/mL, 31.4 μM), low cytotoxicity (LC~50=~\>200 μg/mL, \>423.7 μM). Additionally, this compound showed high antioxidant activity through ORAC and DPPH methods. These experimental results motivated us to carry out computational explorations such as docking against several parasite protein targets, molecular dynamics to validate docking results and DFT calculations, used to explain the high antioxidant activity of chromone. Notably, the docking results showed the N-myristoyltransferase (NMT) enzyme to be a potential target for chromone (docking score −9.1 kcal.mol^−1^). Molecular dynamics (MD) studies provide strong evidence of the conformational stability of the chromone-LpNMT complex obtained from docking throughout 50 ns all-atom MD simulation. Molecular mechanics Poisson-Boltzmann surface area (MM-PBSA) analyses of chromone-LpNMT complex show that the interaction between the ligand and the target protein is stable. DFT calculations allow to explain the greater in vitro antioxidant properties, and drug-likeness studies show suitable pharmacokinetics properties for chromone. Our findings suggest that chromone has great potential to continue in the search for new drugs to treat leishmaniasis.

## Citation

> Cardona‐Galeano, W., Yépes-Pérez, A. F., Quintero‐Saumeth, J., Robledo, S. M., Alzate-Guarin, F. A., & Rojano, B. (2022). A biologically active chromone from *Bomarea setacea* (Alstroemeriaceae): Leishmanicidal, antioxidant and multilevel computational studies. *ChemistrySelect*, 7(45), e202203852. https://doi.org/10.1002/slct.202203852

