---
title: "Antileishmanial and cytotoxic activities of four Andean plant extracts from Colombia"
type: "article"
author:
  - name: Wilson Cardona-Galeano
  - name: Sara Robledo
  - name: "**Fernando Alveiro Alzate-Guarin**"
    orcid: 0000-0002-4916-8897
  - name: Andrés F. Yepes
  - name: Cristian Hernandez
  - name: Ivan Dario Velez
  - name: Juan Carlos Calderon
  - name: Isabel Vásquez Tabares
year: 2020
date: 2020-10-19
publication: Iranian Journal of Pharmaceutical Research
doi: https://doi.org/10.22037/ijpr.2020.113745.14466
materials: ""

categories:
  - Araliaceae
  - Chrysobalanaceae
  - Lauraceae
  - Rubiaceae
  - Leishmaniasis
  - Licania salicifolia
  - Oreopanax floribundus
  - Persea ferruginea
  - Psychotria buchtienii
---

## Abstract

**Background and Aim:** *Licania salicifolia* (L.S) Cuatrec., *Persea ferruginea* (P.F) Kunth, *Oreopanax floribundus* (O.F), and *Psychotria buchtienii* (P.B) belong to the families Chrysobalanaceae, Lauraceae, Araliaceae, and Rubiaceae, respectively, which have been used as medicines by communities in the Andes. This study evaluated the leishmanicidal and cytotoxic activities of alcohol and non-alcohol extracts from four Andean plant extracts (L.S, O.F, P.F, and P.B).

**Materials and Methods:** Extracts were obtained by percolation with solvents of different polarities -- hexane, dichloromethane, ethyl acetate, and ethanol. Phytochemical screening was conducted based on reported methods. All products were evaluated *in vitro* to determine the leishmanicidal activity against amastigotes of *Leishmania panamensis* and cytotoxicity against U937 cells.

**Results:** Flavonoids, triterpenes, and tannins were the main secondary metabolites found. From the results, dichloromethane extracts from O.F and P.B, ethanol extract from P.B, and ethyl acetate extracts of all plants were active, with EC~50~ \<30 μg/mL. Ethyl acetate was the most active extract, which showed EC~50~ values of 9.8, 14.1, 23.7, and 25.5 μg/mL, for L.S, P.B, O.F, and P.F, respectively. Hexane extracts from P.B and O.F exhibited moderate activity with EC~50~ values of 84.8 and 87.4 μg/mL, respectively. Hexane and ethanol extracts from O.F, ethyl acetate, and ethanol extracts from L.S, and all extracts from P.F were not toxic. Alternatively, hexane and dichloromethane extracts from L.S and P.B as well as dichloromethane and ethyl acetate extracts from O.F displayed high toxicity.

**Conclusion:** Based on the activity we observed, ethyl acetate extract can continue in its usage in the search for new antileishmanial drugs, mainly ethyl acetate extract from L.S showed activity comparable to meglumine antimoniate and was not cytotoxic.

## Citation

> Cardona-Galeano, W., Robledo, S., Alzate-Guarin, F. A., Yepes, A. F., Hernandez, C., Velez, I. D., Calderon, J. C., & Vásquez-Tabares, I. (2020). Antileishmanial and cytotoxic activities of four Andean plant extracts from Colombia. *Veterinary World*, 13(10), 2178--2182. https://doi.org/10.14202/vetworld.2020.2178-2182