---
title: "In vitro antiviral activity against SARS-CoV-2 of plant extracts used in Colombian traditional medicine"
type: "article"
author:
  - name: Lizdany Flórez-Álvarez
  - name: Jahnnyer Martínez-Moreno
  - name: María I. Zapata-Cardona
  - name: Elkin Galeano
  - name: "**Fernando Alveiro Alzate-Guarin**"
    orcid: 0000-0002-4916-8897
  - name: Wildeman Zapata
year: 2022
date: 2022-02-06
publication: Vitae
doi: https://doi.org/10.17533/udea.vitae.v29n1a347854
materials: ""

categories:
  - SARS-CoV-2
  - Plant extract
  - Antiviral agents
  - Ethnobotany
---

## Abstract

**Background:** Coronavirus infectious disease 2019 (COVID-19) caused by the infection with the new coronavirus SARS-CoV-2 has affected the life and health of more than 222 million people. In the absence of any specific pharmacological treatment, the need to find new therapeutic alternatives is clear. Medicinal plants are widely used worldwide to treat different conditions, including COVID-19; however, in most cases, there are no specific studies to evaluate the efficacy of these treatments. **Objective:** This article evaluates the antiviral effect of six plant extracts used by indigenous and afro Colombian people against SARS-CoV-2 *in vitro*. **Methods:** The antiviral effect of six extracts prepared from plants used in Colombian traditional medicine was evaluated against SARS-CoV-2 through a pre-post treatment strategy on the Vero E6 cell line. Once cytotoxicity was established through an MTT assay, the antiviral effect of the extracts was calculated based on the reduction in the viral titer determined by plaque assay. **Results:** *Gliricidia sepium* inhibited SARS-CoV-2 in a 75.6%, 56.8%, 62.5% and 40.0% at 10 mg/mL, 8 mg/mL, 6 mg/mL, and 2 mg/mL, respectively, while *P. tuberculatum* treatment reduced viral titer in 33.3% at 6 mg/mL after 48h. **Conclusion:** *G. sepium* and *P. tuberculatum* extracts exhibit antiviral activity against SARS-CoV-2 *in vitro.*

## Citation

> Flórez-Álvarez, L., Martínez-Moreno, J., Zapata-Cardona, M. I., Galeano, E., Alzate-Guarin, F. A., & Zapata, W. (2022). In vitro antiviral activity against SARS-CoV-2 of plant extracts used in Colombian traditional medicine. *Vitae*, 29(1). https://doi.org/10.17533/udea.vitae.v29n1a347854