---
title: "<i>Allomaieta isauroi</i> (Melastomataceae, Cyphostyleae): a new species from the Andean-Amazonian Foothills of Colombia"
type: "article"
author:
  - name: "**Jhon Steven Murillo-Serna**"
    orcid: 0000-0003-4512-5811
    url: /people/murillo-serna_jhon-steven/index.qmd
  - name: "Edwin Trujillo-Trujillo"
  - name: "**Heriberto Antonio David-Higuita**"
    orcid: 0000-0002-2430-2973
    url: /people/david-higuita_heriberto-antonio/index.qmd
  - name: "Oscar Perdomo"
  - name: "Humberto Mendoza-Cifuentes"
year: 2025
date: 2025-07-22
publication: "Phytotaxa"
doi: https://doi.org/10.11646/phytotaxa.711.1.6
materials: ""

categories:
  - Caquetá
  - Endemism
  - Eudicots
  - Flora of Colombia
  - Taxonomy
---

## Abstract

*Allomaieta isauroi*, a new species of Melastomataceae (Cyphostyleae) is
described and illustrated. The new taxon is only known from the Andean-Amazonian
foothills on the eastern slopes of the Eastern Cordillera of the Colombian
Andes. This is the second species described in this area, and it can be
distinguished from the other previously described species by the combination of
leaf blades with one pair of suprabasal, secondary veins plus a marginal pair,
turbinate flower buds, petals light pink basally white, and apically obtuse
anthers. *Allomaieta isauroi* has a restricted distribution and is endangered
due to habitat loss.

## Citation

> Murillo‐Serna, J. S., Trujillo-Trujillo, E., David-Higuita, H. A., Perdomo,
> O., & Mendoza-Cifuentes, H. (2025). *Allomaieta isauroi* (Melastomataceae,
> Cyphostyleae): A new species from the Andean-Amazonian Foothills of Colombia.
> *Phytotaxa*, 711(1), 81–88. https://doi.org/10.11646/phytotaxa.711.1.6
